site_name: nat-zero
site_description: Scale-to-zero NAT instances for AWS
repo_url: https://github.com/MachineDotDev/nat-zero
theme:
  name: material
  palette:
    scheme: default
nav:
  - Home: INDEX.md
  - Architecture: ARCHITECTURE.md
  - Performance: PERFORMANCE.md
  - Terraform Reference: REFERENCE.md
  - Testing: TESTING.md
  - Examples: EXAMPLES.md
