site_name: nat-zero
site_description: Scale-to-zero NAT instances for AWS
repo_url: https://github.com/MachineDotDev/nat-zero
theme:
  name: material
  palette:
    scheme: default
nav:
  - Home: index.md
  - Architecture: architecture.md
  - Performance: performance.md
  - Examples: examples.md
  - Terraform Reference: reference.md
  - Testing: testing.md
