name: Manual PR Checks

on:
  pull_request:
    types: [labeled]

permissions:
  contents: read
  id-token: write

jobs:
  integration:
    if: ${{ github.event.label.name == 'integration-test' }}
    uses: ./.github/workflows/integration-tests.yml
    secrets: inherit
    with:
      checkout_ref: ${{ github.event.pull_request.head.ref }}

  nat-images:
    if: ${{ github.event.label.name == 'nat-images' }}
    uses: ./.github/workflows/nat-images.yml
    secrets: inherit
    with:
      checkout_ref: ${{ github.event.pull_request.head.ref }}
